# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-06 09:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20171101_0512'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='eEndDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 12, 6, 9, 38, 55, 615840)),
        ),
        migrations.AddField(
            model_name='items',
            name='eStartDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 12, 6, 9, 38, 55, 615816)),
        ),
    ]
